### ISSUE TITLE
Bug: Utilities dialog too long to fit on screen

### ISSUE THREAD

**Issue by pedrocadiz13** [section83/MacYTDL#20]
The Utilities dialog  is too long to fit on screen on my 15@ MacBook Pro. I need to hide the dock in order to access the buttons.

**Comment by section83** [comment]
Currently the Utilities and Settings dialogs show in the centre of the screen.  You probably have more problem with the Settings dialog which is longer than Utilities.  You must be using a quite low resolution as the Utilities dialog is only 350 pixels high.

Anyway, I've changed the positioning of both Utilities and Settings so that they open in the same location as Main.  You can change Main's location by just moving it then doing something else e.g. opening Utilities or Settings or Quit.  So, if you position Main towards the top of the Desktop, Utilities and Settings will display there also.

Cheers.

**Comment by pedrocadiz13** [comment]
The Utilities dialogue is way bigger than 360 pixels, see screenshot: 

<img width="644" alt="Screenshot 2020-06-09 at 21 00 54" src="https://user-images.githubusercontent.com/43679847/84194222-9e8ace00-aa94-11ea-860b-3fce4a24cb12.png">

Its being padded out by  the  Version Installed section.

**Comment by section83** [comment]
Yikes !  That is not normal.  I've just downloaded MacYTDL, launched then opened Utilities.  It displays normally.  So, this will be hard to diagnose.  Anyway, I know where that text comes from and I'll try to find out why it is being displayed in the Utilities dialog.

I have a few questions:

- Can you tell me what your language settings are ?
- Does the Utilities dialog look this way **every** time you open it ?
- Which version of macOS are you using ?

Many thanks.

**Comment by section83** [comment]
I suspect the copy of FFmpeg.  Although the version of yours is the latest, the compiling detail is different – maybe the Audacity process downloaded from a different location.

Anyway, I need to work up a bug-fix which will take a while.  In the meantime, you can stop the problem by deleting your copy of /usr/local/bin/ffmpeg and installing another from here:

[https://evermeet.cx/ffmpeg/ffmpeg-4.2.3.zip](url)

Or, you can start MacYTDL which will do the download and install for you.  Either way you will need to supply admin credentials.

Many thanks for making contact.

Cheers.

**Comment by pedrocadiz13** [comment]
Hi

Replacing ffmpeg with the one from the comment above worked thanks, much better.

Cheers.

**Comment by section83** [comment]
I am glad it's working.  I hope to implement a bug fix in v1.15.

**Comment by section83** [comment]
Problem was MacYTDL code assumed all copies of FFmpeg came form same source and had same version text. That was incorrect and code has been updated to handle copies of FFmpeg "brewed" independently.
