### ISSUE TITLE
Problem Installing MacYtdl Catalina

### ISSUE THREAD

**Issue by knitty-cat** [section83/MacYTDL#25]
Hi, 

i tried installing macytdl and got this error when launching it.  
![Bildschirmfoto 2021-01-27 um 08 44 21](https://user-images.githubusercontent.com/49856874/105959696-8c3dbe80-607c-11eb-8df0-dce577e4a8a1.png)

I am trying to uninstall the programm by deleting every part of it manually, but no luck.
Maybe i didnt uninstall it completely?

Something strange i found was, that in the "automation" permission, there is no checkbox for the Finder.
![Bildschirmfoto 2021-01-27 um 08 44 33](https://user-images.githubusercontent.com/49856874/105959955-dcb51c00-607c-11eb-854f-254189c293b9.png)

Maybe a permission issue?

What can i do to manually remove MacYTDL and try it again cleanly?

Greets,
Alex

**Comment by section83** [comment]
Sorry you have had this problem. To be sure I understand the error, could you please provide a translation of the error message.

I have just downloaded and installed MacYTDL on a vanilla Mac running macOS 10.13.6. I had no errors. What version of macOS are you using ?

There is a full list of all the components and their locations in the “Help” file in the dmg file.

Luckily, “word 1” is used only twice in the AppleScript code. So, the error could be in one of those places. Are you able to use the Terminal application on your Mac? If so, please try this command in Terminal:

system_profiler SPDisplaysDatatype

It should return detail about your Mac’s display. Please copy and paste that detail in a response to this post.

Many thanks.

Garry

**Comment by knitty-cat** [comment]
Hi Garry,

I am running 10.15.7. . I think the problem is, that MacYTDL has no permission to control the Finder. So it cant get the ScreenBounds or the SystemTime?
Do you know a way to add the Finder permissions back to MacYTDL?

The Terminal doesnt output anything with "system_profiler SPDisplaysDatatype". But no error either. Maybe i am missing something. 

Thank you very much for our support!!

Alex

**Comment by knitty-cat** [comment]
The message says "word 1 of """ cant be read"

**Comment by section83** [comment]
`The Terminal doesnt output anything with "system_profiler SPDisplaysDatatype".`

Oops, my mistake sorry.  The system_profiler command is very case sensitive.  Open Terminal and try this:

> system_profiler SPDisplaysDataType

`Do you know a way to add the Finder permissions back to MacYTDL?`

You should not need to do anything until asked to provide permission.  When asked, click on the "OK" button.  If you click on "Don't Allow", "Finder" should still appear under MacYTDL in Automation permissions.  You can tick the box any time.

It will be difficult to find the cause of the problem because it all works perfectly on my Mac running 10.15.7.  There is a clue in the error message which refers to "word 1" of "" can't be read.  I don't think it is caused by lack of permission to control Finder.  But, it still might be a permission issue.

Are you able to use the "Script Editor" application ?  If so, please try this:

- open Script Editor
- choose File/Open and choose MacYTDL
- choose View/Show Log
- press command-r [which will run the code]
- wait for the error to appear
- if an error dialog is displayed click on OK or cancel as appropriate
- click on the "Replies" button at the top of the "Log" pane [in the bottom section of the window]
- select and copy all the text appearing in the Log pane

Send the text to me by email to macytdl@gmail.com.

That text will help me understand the problem.

Many thanks.

**Comment by knitty-cat** [comment]
i think i got it, 
im on the machine over teamviewer and the monitor is off. 
For the first start of MacYTDL you need the Monitor-resolution maybe?

**Comment by section83** [comment]
Thank you for running those two tests for me.  It has confirmed that my method for using system_profiler is the cause of the problem.

Yes, I use the system_profiler to get the screen resolution data – so that I can position the MacYTDL dialogs correctly on single and dual monitor setups.  The Finder doesn't provide enough detail on dual monitor setups.

Should have a fix ready in a day or two.

In the meantime, if you wish to use MacYTDL on that Mac, connect a monitor and the MacYTDL startup should work properly.  It will find the components which have been installed and for those which have not, will ask for your agreement to install them.  When necessary it will ask for permission to control the Finder.

Many thanks.

**Comment by knitty-cat** [comment]
Hi Garry,

the new version works like a charm!
Everything working over TeamViewer with no monitor connected.

**Comment by section83** [comment]
Beaut !  I'll update that release to v1.16.1.

Cheers
