### ISSUE TITLE
Playlist Crash

### ISSUE THREAD

**Issue by barney1903** [section83/MacYTDL#28]
Hi, I love this GUI and how easy it is to use. When I download a YT playlist with 5 videos, it works perfectly. But when I try with 20+ videos, when I click continue, the button just appears dark (implying I've clicked it and it's crashed) and then I right-click the program in the dock and it says application not responding. 

<img width="284" alt="Screen Shot 2021-04-15 at 9 07 44 pm" src="https://user-images.githubusercontent.com/68524770/114859878-a6db3480-9e2e-11eb-92c1-d802dd040452.png">
<img width="479" alt="Screen Shot 2021-04-15 at 9 07 32 pm" src="https://user-images.githubusercontent.com/68524770/114859894-a9d62500-9e2e-11eb-8220-60251ab235e5.png">

**Comment by section83** [comment]
Thank you for this report.  As it turns out, it wasn't a crash but, there are bugs to be fixed.

The playlist you were trying to download has 342 items.  MacYTDL does a "simulate" download on each item to make sure there are no problems and to get the names of the items.  It takes 1-2 seconds per item and so, it might take 10 minutes to do the simulate on a slow Mac.  During the simulate MacYTDL is waiting and so macOS reports it's "not responding".  If you've not done another download, you can see the results of the simulate in this file: [Your Mac]/Users/[Your Home]/Preferences/MacYTDL/simulate.txt.

I should add a message or warning about very long playlists so that users know it will take a long time.

After the simulate, MacYTDL does a pile of work then forms up the call to youtube-dl.  With 342 items, that can take another 5 minutes during which time the MacYTDL window is not visible.  There can be more delay if there are warnings.  That playlist did cause one warning:

![Warning](https://user-images.githubusercontent.com/7471595/114953560-f7d54200-9e9b-11eb-8330-dab354069ba3.png)

But, that's not a real warning so, it's a bug I need to fix.

I clicked on "Continue" and continued the test.  After another 5 minutes or so, the download started.

![Progress](https://user-images.githubusercontent.com/7471595/114953504-da07dd00-9e9b-11eb-9c70-a3cb5ea97952.png)

Note that the progress reported is on each item in turn.  In this example, 14.6% of one item in the playlist had been downloaded when I did the capture.

Again, many thanks for the report.  I'll put fixes into the next release.

Cheers.

**Comment by barney1903** [comment]
Thanks for that amazingly thorough reply. I will give it another go and just let it run for longer. If it doesn't work I'll just break the playlist down into smaller ones.

Is there a link that I can donate to, would love to buy you a beer/coffee, it blows my mind that you are doing this for free.

**Comment by section83** [comment]
I'm not sure MacYTDL handles part of a playlist.  One of the ideas I've had is to implement the YTDL option of specifying playlist items to be downloaded.  In the meantime you could do it yourself using Terminal with this command, which would download items 1 to 30 to your home folder:

youtube-dl -v --playlist-items 1-30 "https://www.youtube.com/playlist?list=PLaUm0baL9EpWDZRgaoHF4G49TVPsiZCUT"

[the "-v" requests verbose feedback from youtube-dl]

If you don't have download monitor software, you could consider tools like LittleSnitch.  A download monitor will let you know that data is being downloaded/uploaded and by which apps.  With that, you will know that MacYTDL is processing – note that the downloads are actually done by processes called "Python" and "FFmpeg" depending on how the video files are served.

MacYTDL is a retirement project for me and will always be free.  It's very satisfying to know that people find it useful.  If you happen to use shareware/donationware software send them some money.  Alternatively, you could make a donation to any free news/info sites you frequent (e.g. Wikipedia, who are always short of funds).

Cheers.

**Comment by barney1903** [comment]
Thanks again for the detailed reply. However, your first recommendation solved it all, all I had to do was be patient, the entire playlist is now in my files.

Amazing attitude to have, I'm a regular donator to anyone that provides an incredible free solution online. 

Since I can't donate to you, I will provide you with this.

https://github.com/master131/iFakeLocation
This file was created to change your phone's location, the main purpose of it is to lock in a fuel price through the 7/11 app in order to save money on fuel. 

Here is a link to read more; https://www.ozbargain.com.au/node/288802?page=107#comment-8884089

**Comment by section83** [comment]
Many thanks.  I've hidden your links as this GitHub page is published to the world.

Cheers.
