### ISSUE TITLE
[Feature Req] option to minimize the app window and the downloading window....

### ISSUE THREAD

**Issue by zxzzz8** [section83/MacYTDL#31]
using v1.17, high-sierra 10.13.6 .
idk if its even a bug, but i have no way to minimise any of the windows of the app, i used the 'hide' option on the dock, but that works only for the app main window, for the little download window if i click on the 'log' option it closes it, but then no way to reopen it.... and that download window keep reseting to the same position as well if i leave it, i even tried to move it to another space in the mission control, but the main window dissapear when i enter mission-control, and the download window reset b to the original space, to begin w i have mac-mini w a normal mouse so i don't have a way to do swipe set up and therefor never really use spaces.... i just want the ability to minimize it w the usual yellow botton in the corner.... XD

**Comment by section83** [comment]
Yes, the small download window (I call it the "Monitor") can't be minimised or hidden. That's a limitation of the tool I'm using to create the dialog ([the DialogToolkit](https://latenightsw.com/freeware/)). The toolkit only creates modal windows. I do have a plan to change that but, it involves learning some AppleScript Objective C. Complicating things further, the Monitor dialogs are separate processes created by a background call to the shell (using osascript).  That enables you to control each download separately (normally, AppleScript is single threaded).  The MacYTDL main, utilities and settings dialogs are in an applet which can be hidden but not minimised.   If I can enable the Monitor dialog Ito be minimised, I can also change the others.

The Monitor dialog reappears at the same position because it's doing a refresh and redisplay every 5 seconds. AppleScript can't update such a dialog without closing it, updating variable and redisplaying.  I can change how often it updates perhaps to 7 seconds or more.  I should also be able to get it to save its position and redisplay in the new position.  The other dialogs already do that.

I'm also planning to have Monitor dialog redisplay after you press on the "Logs" button instead of disappearing permanently – usually leaving a download running that can't be stopped (without using Activity Monitor).

I agree that a modal window is not friendly and it would help to save the position.  So, I'll push those changes up the todo list.

Many thanks.

**Comment by zxzzz8** [comment]
thank you ^^

actually another thing that happened to me in the past few hours, when a download finished it popped a little window w some options while i was writing text so it ended up receiving my keyboard input instead of the app i was originally in, i didn't use 'enter' then, but i used 'space', n i guess it treated it like 'enter'? coz that window dissapeard almost as soon as it showed up, opening the logs folder instead in front of me and removing the focus from the app i was at, that felt very not user friendly XD

in general i think a little alert window popping up in the front while im doing other stuff seems very intrusive,
mby at least as a temporary solution, an option to disable that finishing-download alert? 

in addition to instead adding in the log file a line to inform the process is all done?

actually it would be really nice to have that ending log line w a timestamp as well to know when it finished the download, 
that ending log line actually would be really awesome regardless i think, 

also mby putting a timestamp on all the lines of the log would also be nice? 

at least there is already a timestamp at the logfile name so you know the start point, so add to that at least the end time, and that would be really usefull, for example if i wanna know how long it took when i left it overnight etc.... =3

**Comment by section83** [comment]
Yes, that pop-up when a download is finished can be annoying. So, thanks for mentioning it.

I'll think about less intrusive alternatives.  I'd like to use the macOS Notifications facility but, access to that from AppleScript is quite limited.  I could use the existing "Monitor" progress dialog – leave it showing for a short while with the three functions currently provided by the pop-up.  The current dialog pops-up in the middle of the screen because there is no way to set the position using the current code (a simple "display dialog" command in AppleScript). A setting to control whether the pop-up appears should be easy - but might not be necessary if I can get notifications working or change the Monitor.

The log file is written by youtube-dl, not MacYTDL. So, I don't know if I can change what it writes out in each line.  However, adding something extra at the end should be doable - open the log file, go to the end, add a new line, add some text like a timestamp.  I'll put that idea into the "todo" list.  Getting the timestamp might be the hardest bit as youtube-dl doesn't report when it's finished. MacYTDL tracks the Python process spawned for the download and senses when that process has quitted.  It checks every 5 seconds.  The log file does report how long the download took, for example:

`[download] 100% of 126.58MiB in 00:27`

Also, Finder has a "Date Modified" option in windows' List, Columns and Gallery views.

With Finder dialogs, the space bar invokes a button which has a "ring" around it.  Users can move that "ring" using the tab key (depending in their settings in Keyboards=>Shortcuts).  The return key invokes the default button which is usually solid and can't be moved by the user.  So, dialogs can look like this:

![Dialog](https://user-images.githubusercontent.com/7471595/117222532-fc639980-ae4e-11eb-8cea-b6eabbcb16f6.png)

Thanks.

**Comment by zxzzz8** [comment]
oh r it does say the total time in the log, thats nice, i might have missed that XD .

i just have a habit of giving timestamps for everything.... i have a hotkey im constantly using in BetterTouchTools app on my mouse to paste a timestamp like this [12021-05-06 05.46.20][12021-05-06 05.46.21] (and ye i have a mouse w a bunch of extra keys on the side for stuff like that XD , my favorite is 'copy' n 'paste' in the mouse lol)

and ye that ring-marker that makes 'space' pick an option, does makes this sudden alert way worst then, considering the intrusive situation of it. XP

**Comment by section83** [comment]
Yes, it's definitely going to be fixed.

I always use the verbose option.  Perhaps YTDL doesn't report time taken with verbose off.  Make sure verbose is on – it doesn't cost anything and it provides a lot more clues when things don't work as expected.

**Comment by zxzzz8** [comment]
oh so that 'verbose' setting is related to the log file? ill try it then ^^ 
wasn't sure what that setting was, as its name wasn't clear to me = P

**Comment by section83** [comment]
I've tried to explain everything in the "Help" guide.  Maybe I should convert it to a wiki ?

There are more YTDL settings "--dump-pages" which is like an extremely verbose report, it prints downloaded pages encoded using base64.  There's also "--write-pages" which writes downloaded intermediary pages to files and lastly "--print-traffic" which according to YTDL readme will, "Display sent and read HTTP traffic". I've not played with any of those so, they are not in MacYTDL.

Anyway, have a good weekend.

**Comment by section83** [comment]
I'm working on replacing the current "Download finished" dialog, which can be annoying, with Notification.  If the download works, it will have option to play the video.  If download has an error, it will have option to open the log file as at present.  It might look like this:

![Notify](https://user-images.githubusercontent.com/7471595/119067518-a7667c80-ba25-11eb-9acc-451995cf37a7.png)

A macOS compliant notification is much better then the current dialog which can interrupt work etc.  Users can then decide whether or how to show the notifications (in system Preferences).

**Comment by section83** [comment]
Now in bug list and list of changes.
