### ISSUE TITLE
[Bug?] thumbnail embeding option missing?

### ISSUE THREAD

**Issue by zxzzz8** [section83/MacYTDL#32]
i don't think its that important of an issue at all i guess? but when it show the options before the download, it have beside the getting the thumbnail, another option of embedding it, but i didn't see any such option in the actual settings page.... mby im just blind? but i looked multiple times very carefully on every option there....

i also noticed there is that option set on negative in the MacYTDL.plist file, but mby its just expirimental option or something? so i didn't touch that.... i just thought that the inconsistency between the settings page n settings preview before download might not have been intentional, but if it is then sorry for the bother....

**Comment by section83** [comment]
No, you're not blind.  The "Embed thumbnails" setting is only visible if you have _Atomic Parsley_ installed.

- Go to Utilities,
- tick the "Install Atomic Parsley" box and click on "Start",
- when asked enter the username and password of an administrator account on your Mac then click on "OK".
- quit MacYTDL and re-open (that's a bug I'll fix soon).

You should see the "Embed thumbnails" option in the Settings dialog.

Let me know if it doesn't work as you expect.

Many thanks.

**Comment by zxzzz8** [comment]
i tried, it did show, but when i tried to mark it and click save, it gave me this error and didn't do it:
''Sorry, to embed thumbnails, File format must be mp4 or Remux format must be mp3, mp4 or m4a.''

i have my file format set on ''default'' so that it will do the native file format per site etc, i mean thats what deafult mean here r?

so i think it should instead just warn when its default, that it will only embed when this is the file formats, and not cancel the setting entirely, at least when its set to this default option....

**Comment by section83** [comment]
Thanks. I'll look at it the logic.  There is a bug in the "Settings" dialog – it should make the Embed Thumbnails setting visible as soon as Atomic Parsley is installed and not require a restart.  Also it should not require a remux as remuxes are not available into audio files – my bad – I changed how remuxes work but forgot to update the Embed Thumbnail function.

I'll have a fix in v1.18.

**Comment by zxzzz8** [comment]
i think you should also add a warning line next to the download thumbnail option, that only show when the app doesn't have AtomicParsley installed yet, stating ''you need AtomicParsley to embed it....''. 
because at first sense there was only one setting about the thumbnail it made me assume it will also embed it then, so that will clarify things a lot.... both to why you need AtomicParsley as well as how to get the thumbnail embedded, so that an end-user can easly understand the situation, and not finding that up after trying to download something and wonder what went wrong....

**Comment by section83** [comment]
OK, I think I've got it settled. To embed thumbnails in audio files, _Atomic Parsley_ must be installed.  Specifying mp4 file format often doesn't work because it's not available – YouTube downloads for example are usually mp4/webm video only and webm audio only files that are merged to mkv even though I specify mp4 in file format. Also, I can't get embedding to work when remuxing to mp4 (I've commented on that on YTDL's Issues).

So:

- MacYTDL will turn off the "Embed thumbnails" setting if _Atomic Parsley_ is removed.
- "Embed thumbnails" is only accepted if "Audio only" is on and "Audio format" is m4a or mp3.
    - I highly recommend against remuxing audio only files using MacYTDL - result can be a mess.
- "Settings" will only show the "Embed thumbnails" option if _Atomic Parsley_ is installed. Otherwise, that part of the dialog is blank.
- Installing _Atomic Parsley_ at any time will enable the  "Embed thumbnails" option in "Settings".

My ToDo list includes providing a way to recode codecs inside containers.  For example, I'd like to recode the Opus audio codecs that are usually inside an MP4 container created from YouTube into m4a.  But, recoding takes a lllloooonnnnggg time ! My 11 yo iMac took 15 minutes to recode the codecs inside one small mp4 container.  So, I've not implemented that change as yet. Maybe when I get an M2 iMac :smiley:.

**Comment by zxzzz8** [comment]
> "Settings" will only show the "Embed thumbnails" option if Atomic Parsley is installed. Otherwise, that part of the dialog is blank.

what i was trying to say in the previous message, was that leaving it 'blank' like you said is a bad idea i think, sense you want to inform the user there exist such setting if they install 'Atomic Parsley'.... 
or else they either not know it even exists, or they will wonder where that setting is like i did before i opened the issue here, n many end-users might not come here for a solution about it like i did, i think its a necessary thing for it to be a polished user friendly result....

**Comment by section83** [comment]
You are right. I've changed "Settings" so that the "Embed thumbnails" option is always visible. But it can only be set on if _Atomic Parsley_ is installed, "Audio only" is on and "Audio format" is mp3 or m4a.

Pity it's so limited but, I can't get YTDL to do anything else.  People have reported it's a problem – all we can do is wait for the YTDL developers to consider the issue and implement a change.

Many thanks for your thoughts. It helped me decide what to do and why.

**Comment by section83** [comment]
Thumbnails can only be embedded in audio files (as per YTDL specifications) and now, the option is always visible.
