### ISSUE TITLE
Possible YT-DLP Support?

### ISSUE THREAD

**Issue by TomasCarlson** [section83/MacYTDL#41]
Love this tool!

Seeing as [yt-dlp](https://github.com/yt-dlp/yt-dlp/) seems to be more maintained than the original youtube-dl repo (which hasn't been updated in quite some time), would it be possible to also add support for yt-dlp's unique features? As of now, I'm using the app with yt-dlp replacing youtube-dl's commands

**Comment by section83** [comment]
Thank you for making contact.  Yes, yt-dlp looks good.  I don't know what is happening with youtube-dl – they seem to have dropped out of sight.

My main concern with yt-dlp is that for some functions it requires Python 3.6 which is not standard on macOS. I have been planning to add Python 3.6 – because Apple have warned for some time that they will omit Python 2.7 from a future version of macOS. But, till now I've not done any work on that.  So, I guess it's time to get serious and work up a way for users to install Python 3.6. That might take quite a lot of research and coding and so take time.

In the meantime, you can install and use yt-dlp with _MacYTDL_ yourself right now:

- download yt-dlp from the most recent release [available here.](https://github.com/yt-dlp/yt-dlp/releases/download/2021.08.10/yt-dlp)
- rename it youtube-dl.
- save it in "usr/local/bin" (you will need to supply admin credentials).
- in Terminal type this (so that it becomes executable): chmod a+x /usr/local/bin/youtube-dl

_MacYTDL_ doesn't check whether the executable really is youtube-dl – it will use anything with that name.

I'll add new settings to _MacYTDL_ for config files and maybe also custom runtime YTDL options.  That way you will be able to try out any of the new yt-dlp options. Hopefully, I'll have config files available in the next release.

Cheers.

**Comment by section83** [comment]
_YT-DLP_ is available for use in version 1.19. Requires macOS 10.15 or higher.
