### ISSUE TITLE
Unable to update / install 1.19.1

### ISSUE THREAD

**Issue by heviiguy** [section83/MacYTDL#48]
Mac OS: 10.15.7

I'm currently running with v 1.18. When attempting to update as the app recommends, I'm greeted by:

"curl: (3) URL using bad/illegal format or missing URL"

The same thing happens after manually installing 1.19.1 from git hub

**Comment by section83** [comment]
I'm sorry, you are having trouble.

I can't replicate the error. Can you help with some more details ?

- Do you see this dialog ?

![Update](https://user-images.githubusercontent.com/7471595/146462878-e19e03ec-79be-43e1-9580-21470c8db0cd.png)

- Are you using a VPN or proxy ?
  - If so, can you switch it off and try again ?
- Are you accessing the internet via your own modem or via a network (e.g. provided by your employer) ?
- What happens if you choose these Utilities ?
  - "Open YT-DLP web page"/"Open youtube-dl web page".
  - "Check for FFmpeg update".
  - "Check for YT-DLP update" / "Check for youtube-dl update".
  - "About MacYTDL" followed by "Visit Site".

Can you open your web browser and paste this into the address bar:

  https://github.com/section83/MacYTDL/releases/


Many thanks.

**Comment by heviiguy** [comment]
**Thanks**! Going through the utilities, one-by-one, did the trick. _FFmpeg was out of date_. 

After updating FFmpeg, I was able to successfully complete the update of MacYTDL to 1.19.1. The program now works without a problem.

**Comment by section83** [comment]
Great, it's a relief to me that all is working.  Each utility is a separate routine so, I think it was a coincidence.  Anyway, it is best to keep all components up to date so it was useful to update FFmpeg etc.  I'll try to add code which provides a more useful error message.

Cheers.
