### ISSUE TITLE
Error message when updating or installing YT-DLP

### ISSUE THREAD

**Issue by Nellio** [section83/MacYTDL#51]
/usr/local/bin/yt-dlp: line 1: Not: command not found
/usr/local/bin/yt-dlp: line 1: Not: command not found (127)

<img width="416" alt="Capture d’écran 2022-03-21 à 13 30 20" src="https://user-images.githubusercontent.com/2989326/159599633-5ed291ad-9124-45b9-ae5f-b71eb16527e8.png">

Clicking "Modify" or clicking "OK", MacYTDL then quits.

**Comment by section83** [comment]
Thank you for making contact.  Sorry about the problem you’ve encountered.  That is a bug in _MacYTDL_.  It is fixed in the new version (1.21) which I hope to release later this week.

In the meantime, if you are comfortable using Terminal, you can work around the bug using this procedure:

- Download the latest version of YT-DLP from here: https://github.com/yt-dlp/yt-dlp/releases/download/2022.03.08.1/yt-dlp_macos.
- Rename the downloaded file "yt-dlp".
- In Terminal enter this: chmod a+x [type the path to the downloaded copy of YT-DLP in quotes].
- Move YT-DLP to this folder: /usr/local/bin.
- To make hidden folders visible, press command-shift-. [i.e. command-shift-fullstop]
- There is probably a small file called yt-dlp in there. If so, replace it.
- Start MacYTDL and hopefully, all will be well.

Garry

**Comment by thejasonparker** [comment]
Hi @section83 

I just tried the procedure above but get these errors when I try and run MacYTDL.

<img width="284" alt="CleanShot 2022-03-23 at 12 04 00@2x" src="https://user-images.githubusercontent.com/82903/159695100-f0fe4c52-9c90-445e-abe2-595c465facb3.png">

<img width="286" alt="CleanShot 2022-03-23 at 12 03 40@2x" src="https://user-images.githubusercontent.com/82903/159695133-3a0e63ce-07ab-4c2e-85f0-88c7b3cb9aea.png">

I just wanted to notify of this just in case it effects the update.

Thanks - Jason

**Comment by section83** [comment]
Sorry you've had all this trouble.  I have to set up a virtual machine to try to replicate what you've found.  So, it might take a day or so to explain what you should do.

Just in case it helps, make sure yt-dlp is called "yt-dlp – that is, no file extension. Do a Get Info on yt-dlp.  It should look like this:
 
![Info](https://user-images.githubusercontent.com/7471595/159810904-5ce55898-5abe-4402-8104-41ce80470c4a.png)

 I can't begin to explain the second error.  I get that when I'm testing but, not after I've removed the code I use to enable debugging.

So, I'll work on this today and post here when I know why these errors are occurring.

Thanks.

**Comment by section83** [comment]
>I just tried the procedure above but get these errors when I try and run MacYTDL.

OK people, there are some more steps that might be required on some (most) Macs. The errors that thejasonparker had might occur on many other Macs. The solution which worked for me was – If you get the error ""yt-dlp" can't be opened because Apple cannot check it for malicious software"

- open System Preferences;
- choose "Security & Privacy";
- choose "General".

You should see this: ![yt-dlp blocked](https://user-images.githubusercontent.com/7471595/159839083-f2643293-8894-4503-a1c9-0d3c96e57d44.png)
 
- Click on "Allow anyway".
- Start MacYTDL.

You should then see this:
![Can't be opened - open](https://user-images.githubusercontent.com/7471595/159839277-5327a746-35ce-4941-8c84-8d76460942a0.png) 
- Click on "Open".

MacYTDL should the proceed to open. The exact content and presentation of the dialogs will be different in different versions of macOS. However, this procedure should work in all versions from macOS 10.15 Catalina onwards.

There is some more detail provided by Apple here: https://support.apple.com/en-us/HT202491.

Sorry for all the trouble.

**Comment by section83** [comment]
Fixed in version 1.21 (I hope)
