### ISSUE TITLE
Unable to change Default Download Directory in Settings

### ISSUE THREAD

**Issue by alphabitnz** [section83/MacYTDL#53]
OS: macOS Monterey 12.4 Beta (21F5048e)
Version: MacYTDL 1.21, 27 March 2022

Experience:

Folder Dropdown in Settings does not register selection of any parent folder
Selecting 'Choose' and browsing to a new folder causes the below error on 'Save Settings',
followed by application crash (all changes aside from download folder seem to get applied):

```
Can’t set «class plif» "System:Users:myusername:Library:Services:Send-URL-To-MacYTDL.workflow:Contents:info.plist" of application "System Events" to "Send-URL-To-MacYTDL".

System Events got an error: Can’t set property list file "System:Users:myusername:Library:Services:Send-URL-To-MacYTDL.workflow:Contents:info.plist" to "Send-URL-To-MacYTDL". (-10006)
```

**Comment by section83** [comment]
Alphabitnz,

Thank you for making contact.  I've not seen that problem before.  The code behind the drop down is solid ASOC that's been used widely for 3-4 years.

The error might be related to a change in macOS 12.4 beta you are running.  I'm going to set up a copy of 12.4 in a VM today and will try to find out why you are getting the error.  I'll report back as soon as I have news.

**Comment by section83** [comment]
Alphabitnz, still no progress for me in testing on macOS 12.4.

One question though, can you check permissions on the MacYTDL Service "Send-URL-To-MacYTDL" ? The error you got might be due to not having write permission. If that is so, try changing the permission to "Read & Write" and try MacYTDL again.

Thanks.

**Comment by alphabitnz** [comment]
Hi @section83, thanks for responding - I have looked into the ~\Library\Services directory and it is completely empty, not even any hidden files or folders showing in with the ```ls -a``` terminal command

**Comment by section83** [comment]
Thank you for the clue.  I've been able to replicate the error in macOS 12.3.1 So, I know it's not a 12.4 beta issue.

It's a classic bug in which my code doesn't allow for some situations. I got the error when trying to save settings with Auto download off, and no Send-URL-To-MacYTDL.workflow file in the Services folder. The bug will be fixed in the next release.

In the mean time, the only way to workaround the bug is to install the Send-URL-To-MacYTDL service.  Go to Utilities, tick the box "Install Service" and click on "Start". Keeping the service in place puts virtually no load on macOS. It might be useful (although YMMV).

Again, many thanks for reporting this and helping.

Cheers.

**Comment by alphabitnz** [comment]
Awesome, thanks! 
Can confirm installing the service manually as per instructions gets the download folder setting through the 'Choose' option "sticking" correctly.
Worth noting the drop-down selection is still non-functional in both the main and settings windows, even after restarting the app, though that feature is not of concern to me personally.

**Comment by section83** [comment]
> the drop-down selection is still non-functional

Just in case it helps, the folder names listed when you click on the drop down do not do anything.  For example, clicking on "Users" in this will do nothing:

<img width="162" alt="Drop down" src="https://user-images.githubusercontent.com/7471595/162668506-cd679e6a-b339-4fd1-900a-88b82410c8b7.png">

Are you clicking on "Choose..." then navigating to the desire folder ?

The drop down is provided by the Dialog Toolkit script library I use.  The author has advised there is no way to make functional the items shown in a dropdown.

**Comment by alphabitnz** [comment]
Yes 'choose' works after the workaround, if the dropdown selections are not expected to be functional then that's fine.
