### ISSUE TITLE
user interaction disallowed (-1712) error upon launching for the first time.

### ISSUE THREAD

**Issue by ComfortableMilk4454** [section83/MacYTDL#80]
![CleanShot 2024-08-06 at 13 56 21@2x](https://github.com/user-attachments/assets/0c628878-8254-4d1c-b005-ab9c7c77a772)
macOS 15.0 Beta (24A5309e). is this an error i should be concerned about or one i can ignore? tysm!

**Comment by section83** [comment]
Hello ComfortableMilk4454.  Thank you for posting and sorry you've encountered the error.  It's probably a bug created by a change I made in v1.27 of MacYTDL.  I'm going to undo one of those changes.  But, can you tell me a few things:

- Are you able to start MacYTDL and see the main dialog ?
- If so, when do you get the error ?
- If not, did you see any other dialogs ?
- Are you doing something else at the same time in another app which is active/at front ?
- Can you check a macOS setting – MacYTDL allowed to control other apps (System Settings > Privacy & Security > Automation).  It should look like this:
 
![Screenshot 2024-08-07 at 9 34 36 AM](https://github.com/user-attachments/assets/fb5e6493-26c7-47f1-85db-68ecb8ea3717)

Many thanks.

**Comment by ComfortableMilk4454** [comment]
@section83 ty for the response! turns out its caused by macOS 15 beta (at least i think), as i had to restore my mac to macOS 14.6.1 & installed macytdl from here https://github.com/section83/MacYTDL/releases/download/1.27.1/MacYTDL-v1.27.1.dmg & did the same thing as i did when i set it up on the beta & the error didn't pop up. & my macYTDL is allowed to control other apps 
![CleanShot 2024-08-07 at 22 16 47@2x](https://github.com/user-attachments/assets/d5526855-3595-42ea-a414-8c6088f622b1)

i was running macOS Sequoia 15.0 Developer Beta 5 (24A5309e) in case that helps u fix it for the upcoming macOS Sequoia public release in the fall. 

thanks for this wonderful app btw! i use it all the time!

**Comment by section83** [comment]
Many thanks for this.  Bit of a relief to know issue is not in macOS 14. However, I will have to research what changes are needed to be compatible with macO 15.

BTW, the macOS 15 release notes have this:

>To improve security, the process of allowing an application to control Finder has changed. Instead of a modal “Allow/Donʼt Allow” dialog, the attempt to control Finder fails, and a notification appears that directs the user to allow control in System Settings

I can see from your capture that MacYTDL does not have authority to control Finder.  It does need that to download videos etc.  There is no way to add that manually – you have to wait for macOS to show a dialog asking for permission.  When starting MacYTDL on macOS 15, you might find that notification dialog hidden behind other apps.  If by accident a user refuses permission, the only recourse is to use tccutil in Terminal to reset permissions.  macOS has operated that way, I think, since 10.14.

Please let me know if there is a feature you would like added to MacYTDL.

Cheers.

**Comment by ComfortableMilk4454** [comment]
oh weird it downloaded many videos without that authority to control Finder

**Comment by section83** [comment]
As long as it downloads I'm happy !

It doesn't need Finder for all functions.  It does need Finder to open the folder of log files (first function in Utilities).  That should trigger a warning/crash with a dialog like this:

![Screenshot 2024-08-09 at 11 41 50 am](https://github.com/user-attachments/assets/8fcfb514-7a23-40b7-9808-11298447003d)

The design and content of the dialog varies with the macOS version.  it also works differently if it's the first time that permission has been triggered.

Cheers.

**Comment by ComfortableMilk4454** [comment]
oh i see. thanks for letting me know!

**Comment by ComfortableMilk4454** [comment]
this fixed itself in the new beta
