### ISSUE TITLE
Error when trying to download video

### ISSUE THREAD

**Issue by minkses** [section83/MacYTDL#81]
Hi! First of all, I love your work! I've been using MacYTDL for a while and truly cannot sing its praises enough. Without it, I'd be lost on how to use YTDL at all.

That said, I've been running into a strange error whenever I try to download a video recently.
<img width="372" alt="Screenshot 2024-09-15 at 20 29 47" src="https://github.com/user-attachments/assets/053b30a7-dd71-4e57-8b74-d6c2adbf551d">
Following this error, the program simply closes.
I'm on version 1.27.1 on MacOS 14.6.1, I haven't changed any settings in the program recently or the likes, so I'm a bit stumped on what to do.
My apologies if this is user error, I could not figure out how to fix it.

**Comment by section83** [comment]
Hello mikses,

Thank you for posting this issue.  It's a bug – my goof.  I typed "tbe" instead of "the" and my testing didn't find it.  The bug might have been there for a long time.  So, again, thank you for posting.

Very glad MacYTDL is useful for you.  Please post here if you would like any features added to MacYTDL. If I can, I'll add those features to the next or next after release.

Regards,

Garry

**Comment by minkses** [comment]
Thank you so much for the swift response and for your time in general, it's super appreciated!! I'm glad it was an easy fix.
